# .travis.yml for Backend (NestJS API)

language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

services:
  - mongodb  # Example: If using MongoDB

install:
  - npm install

script:
  - npm run test

deploy:
  provider: script
  script: bash scripts/deploy.sh  # Ejemplo de script de despliegue personalizado
  on:
    branch: main
